### ISSUE TITLE
Edit data of languages not save

### ISSUE THREAD

**Issue by ExsyDev** [eboye/laravel-nova-translation-editor#2]
Hello. When I save a message record from database languages table, it writes saved, but nothing changes in the database.. Nova 2.9.2. Table in database is not working,

**Comment by eboye** [comment]
have you ublished the migration and did php artisan migrate of the [laravel-translation-loader](https://github.com/spatie/laravel-translation-loader) ?

Maybe I should add it to readme.md

**Comment by chosten** [comment]
It does not work with existing records.
I can only update a translation the first time, after that it won't update anymore.

**Comment by olivM** [comment]
the issue is the firstOrCreate in the controller ( should be updateOrCreate )

i made a pull request to fix it : https://github.com/eboye/laravel-nova-translation-editor/pull/4

**Comment by eboye** [comment]
@olivM thanks. Merged
